version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.complete
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://debt_user:debt_password@postgres:5432/debt_collection_db
      - REDIS_URL=redis://redis:6379/0
      - XAI_API_KEY=${XAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_VERIFY_TOKEN=debt_collection_webhook_verify_2024
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=debt_user
      - POSTGRES_PASSWORD=debt_password
      - POSTGRES_DB=debt_collection_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatbot
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
